# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiac < Formula
  desc "Artificial Intelligence Infrastructure-as-Code Generator"
  homepage "https://github.com/gofireflyio/aiac"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.0.0/aiac_2.0.0_macOS-ARM64.tar.gz"
      sha256 "386a54e60b92e503cdc2010474d40a54ee4e40c322a59777f4241158b974bdd0"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.0.0/aiac_2.0.0_macOS-64bit.tar.gz"
      sha256 "d34420bd1aee0a41d075f148267dcf84fd65c84bc3ac317b7f8a55970c4b767c"

      def install
        bin.install "aiac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.0.0/aiac_2.0.0_Linux-ARM64.tar.gz"
      sha256 "f7c496e84c73a14effd9fec2555f622ceee26ff81b5213d7e03d6c6176dae133"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.0.0/aiac_2.0.0_Linux-64bit.tar.gz"
      sha256 "bb0da5b8ed5eff4398c4edd552018e8f6b3fbd52472ca04e59ba94a0d7bcdfa8"

      def install
        bin.install "aiac"
      end
    end
  end

  test do
    system "#{bin}/aiac", "--help"
  end
end
