# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiac < Formula
  desc "Artificial Intelligence Infrastructure-as-Code Generator"
  homepage "https://github.com/gofireflyio/aiac"
  version "2.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.5.0/aiac_2.5.0_macOS-64bit.tar.gz"
      sha256 "6f4efe3d24f84d7693abbe0c47054fdd40b7c5fcc3283a27b2766f9d7f5a8732"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.5.0/aiac_2.5.0_macOS-ARM64.tar.gz"
      sha256 "bca70f8cc07620a1863ba79669e0f16286919771593e4838c05a7266d2e9c06d"

      def install
        bin.install "aiac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.5.0/aiac_2.5.0_Linux-64bit.tar.gz"
      sha256 "4c9a3e6dde4d924f0ca1c952028cc5379cddf11abca608f6445655d5cd35c90f"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gofireflyio/aiac/releases/download/v2.5.0/aiac_2.5.0_Linux-ARM64.tar.gz"
      sha256 "de61e5351d38f776092f820425e86eb04a2d6f78d1df71790895bec59a54997f"

      def install
        bin.install "aiac"
      end
    end
  end

  test do
    system "#{bin}/aiac", "--help"
  end
end
